### ISSUE TITLE
NuGet package should be nice

### ISSUE THREAD

**Issue by flyingxu** [nielscup/ShareFile#2]
This should be a useful package, NuGet package should be nice

**Comment by nielscup** [comment]
Yep, you're right and it's about time. I will try to publish it this week. Probably Thursday or Friday. Is that all right?

**Comment by flyingxu** [comment]
cool

**Comment by flyingxu** [comment]
For those whose can't wait to use it:

1. Compile the solution in `Release` build. (it seems that it's ok to skip the Uwp/WindowsStore/... sub projects)
2. run `nuget pack Plugin.ShareFile.nuspec`
3. Then in your solution, open the Package Manager Console and run `Install-Package Plugin.ShareFile -Source D:\pathto\foldername` in both the .Core and os specific projects.

**Comment by flyingxu** [comment]
P.S. Have you considered merging your project with https://www.mvvmcross.com/documentation/plugins/share?scroll=1300 ?

**Comment by nielscup** [comment]
I have added this functionality to some other share plugin at first but it took me too long before it was accepted so I built my own package, we really needed the funtionality. I will be shipping the package today, in a couple of hours, performing some last tests.

**Comment by flyingxu** [comment]
Yes, that's why I think this package should be very useful. 
I'm a fan of MvvmCross and its plugins gain a lot of popularity among MvvmCross users. I would suggest you try PR your code to the plug I mentioned to see what happens.

**Comment by nielscup** [comment]
Done.
