### ISSUE TITLE
Problem with share on iOS

### ISSUE THREAD

**Issue by Cetonis** [nielscup/ShareFile#3]
Hello,
I have encountered an issue with the library. I tried using it as documented in the README. On iOS (the only used system) an exception is thrown:
`Objective-C exception thrown.  Name: NSGenericException Reason: Your application has presented a UIActivityViewController (<UIActivityViewController: 0x7ff620037800>). In its current trait environment, the modalPresentationStyle of a UIActivityViewController with this style is UIModalPresentationPopover. You must provide location information for this popover through the view controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the view controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.
Native stack trace:
	0   CoreFoundation                      0x000000010a7121ab __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000117ec4f41 objc_exception_throw + 48
	2   UIKit                               0x000000010f36c7f2 -[UIPopoverPresentationController presentationTransitionWillBegin] + 3290
	3   UIKit                               0x000000010e7fd19f __71-[UIPresentationController _initViewHierarchyForPresentationSuperview:]_block_invoke + 2458
	4   UIKit                     `

Is there any suggestion how to solve this?
Thank you in advance whoever will answer.

**Comment by nielscup** [comment]
Hi, I haven't seen this issue before. Are you testing it on iPad or iPhone? If I google for this issue I get [this result](https://stackoverflow.com/questions/25644054/uiactivityviewcontroller-crashing-on-ios8-ipads), iPad related. Could you let me know if you get the same error on iPhone?

**Comment by flyingxu** [comment]
I have the same issue on iPad only.

**Comment by flyingxu** [comment]
![simulator screen shot - ipad air - 2018-05-07 at 10 28 06](https://user-images.githubusercontent.com/122225/39682720-2e968b26-51e4-11e8-9ca5-344a92fb4436.png)
Screenshot on iPad
