### ISSUE TITLE
Access to the path "/storage/emulated/0...." is denied on Android

### ISSUE THREAD

**Issue by PatrykZawieja** [nielscup/ShareFile#4]
I had problem: Access to the path "/storage/emulated/0...." is denied on Android (API Level 25).
WRITE_EXTERNAL_STORAGE and READ_EXTERAL_STORAGE permissions doesn't help. 

Finally i solved it changing a localFolder variable in  method WriteFile in ShareFileImplementation  class:
var localFolder = Android.OS.Environment.ExternalStorageDirectory.AbsolutePath;
to
var localFolder = Android.App.Application.Context.GetExternalFilesDir(null).ToString();

**Comment by nielscup** [comment]
The problem is that your app needs to request for permission first. You can do this with [this plugin](https://github.com/jamesmontemagno/PermissionsPlugin). I have added this now to the Android test project as well.
